version: '3.8'

services:
  # Post Service
  post-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/postdb
      - PORT=3000
    depends_on:
      - mongo
    command: npm run dev 

  # MongoDB service
  mongo:
    image: mongo:4.4 
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db # Persist data outside the container

volumes:
  mongo_data: